export const LEADERSHIP_ROLES = [
  "COO",
  "SYSTEM_ADMIN",
  "HR_MANAGER",
  "FINANCE_MANAGER",
  "SUPPLY_CHAIN_MANAGER",
  "LOCATION_MANAGER",
  "CK_MANAGER",
  "CENTRAL_KITCHEN_MANAGER",
  "OPERATIONAL_LEADER",
  "TECHNICAL_DIRECTOR",
  "MARKETING_MANAGER",
];

export const POS_ROLES = [
  "FOH_OPERATOR",
  "FOH_SUPERVISOR",
  "BOH_SUPERVISOR",
  "BOH_ASSISTANT",
  "RESTAURANT_MANAGER",
];

export const isLeadershipRole = (code) => LEADERSHIP_ROLES.includes(code);
